import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app/discover_data.dart';
import 'dart:convert';

void main() => runApp(new DisCoverPage());

class DisCoverPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return new Page();
  }

  @override
  Widget build(BuildContext context) {
    ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);
    // TODO: implement build
    return MaterialApp(
      title: '计算器',
//      home: Scaffold(
//        body: new SingleChildScrollView(
//          child: new Column(
//            children: <Widget>[
//              new Container(
//                  child: new Text(
//                    '发现',
//                    style: new TextStyle(
//                        fontSize: ScreenUtil.getInstance().setSp(40),
//                        color: new Color(0xff333333),
//                        fontWeight: FontWeight.w700),
//                  ),
//                  alignment: Alignment.center,
//                  margin: EdgeInsets.only(
//                      top: ScreenUtil.getInstance().setHeight(60),
//                      bottom: ScreenUtil.getInstance().setHeight(70))),
//              new Row(
//                crossAxisAlignment: CrossAxisAlignment.center,
//                children: <Widget>[
//                  new Expanded(
//                    child: new Container(
//                      margin: EdgeInsets.fromLTRB(
//                          ScreenUtil.getInstance().setWidth(60),
//                          0,
//                          ScreenUtil.getInstance().setWidth(30),
//                          0),
//                      child:
//                          new Image.asset('assets/image/img_parttime_left.png'),
//                    ),
//                    flex: 1,
//                  ),
//                  new Expanded(
//                    child: new Container(
//                      margin: EdgeInsets.fromLTRB(
//                          ScreenUtil.getInstance().setWidth(30),
//                          0,
//                          ScreenUtil.getInstance().setWidth(60),
//                          0),
//                      child: new Image.asset(
//                        'assets/image/img_parttime_right.png',
//                      ),
//                    ),
//                    flex: 1,
//                  )
//                ],
//              )
//            ],
//          ),
//        ),
//      ),
    );
  }
}

class Page extends State<DisCoverPage> {
  List<Data> data;

  @override
  Widget build(BuildContext context) {
    return layout(context);
  }

  @override
  void initState() {
    super.initState();
    loadData();
  }

  loadData() async {
    var url = "http://test.app.api.zhh.zhixinpai.cn/work/lists/discovery";
    http.post(url, headers: {
      'RABITOKEN': '7602be6a4397b4932c491198a822149e',
    }, body: {}).then((response) {
      Map dataMap = json.decode(response.body);
      var data = new Autogenerated.fromJson(dataMap);
//    print("Response status: ${response.statusCode}");
////    print("Response body: ${response.body}");
//    Map userMap = json.decode(response.body);
//    var user = new InitTree.fromJson(userMap);
//    print("老子要的版本号是: ${user.version.Android.download_url}");
//    version = user.version.Android.download_url;
//    request_word = "请求完毕";
      print("Response status: ${response.statusCode}");
      print("Response body: ${response.body}");
      this.data=data.data;
      setState(() {

      });
//      loadDataSuccess(data.data);
    });

//  http.read("http://example.com/foobar.txt").then(print);
  }


  Widget layout(BuildContext context) {
    return new Scaffold(
      body: new SingleChildScrollView(
        child: Column(
          children: <Widget>[
            new Container(
                child: new Text(
                  '发现',
                  style: new TextStyle(
                      fontSize: ScreenUtil.getInstance().setSp(40),
                      color: new Color(0xff333333),
                      fontWeight: FontWeight.w700),
                ),
                alignment: Alignment.center,
                margin: EdgeInsets.only(
                    top: ScreenUtil.getInstance().setHeight(60),
                    bottom: ScreenUtil.getInstance().setHeight(70))),
            new Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                new Expanded(
                  child: new Container(
                    margin: EdgeInsets.fromLTRB(
                        ScreenUtil.getInstance().setWidth(60),
                        0,
                        ScreenUtil.getInstance().setWidth(30),
                        0),
                    child:
                    new Image.asset('assets/image/img_parttime_left.png'),
                  ),
                  flex: 1,
                ),
                new Expanded(
                  child: new Container(
                    margin: EdgeInsets.fromLTRB(
                        ScreenUtil.getInstance().setWidth(30),
                        0,
                        ScreenUtil.getInstance().setWidth(60),
                        0),
                    child: new Image.asset(
                      'assets/image/img_parttime_right.png',
                    ),
                  ),
                  flex: 1,
                )
              ],
            ),

            new Container(
              height: ScreenUtil.screenHeight,

              child: new ListView.builder(itemCount: data!=null?data.length:1, itemBuilder: itemView,physics: new NeverScrollableScrollPhysics(),),
            )

          ],
        ),
      )

    );
  }

  Widget itemView(BuildContext context, int index) {
    if(data!=null){
      Data model = this.data[index];
      //设置分割线
      return new Column(
        children: <Widget>[
          new Container(
            padding: EdgeInsets.only(left: ScreenUtil.getInstance().setWidth(40),top: ScreenUtil.getInstance().setHeight(60)),
            child:  new Row(
              children: <Widget>[
                new Container(
                  child: new Expanded(
                      child: Text(
                        model.title,
                        style: new TextStyle(
                            color: new Color(0xff111111),
                            fontWeight: FontWeight.w700,
                            fontSize: ScreenUtil.getInstance().setSp(30)),
                      )),
//                padding: EdgeInsets.only(left: ScreenUtil.getInstance().setWidth(40)),
//                margin: EdgeInsets.only(),
                ),

                new Text(model.money+"元" , style: new TextStyle(
                    color: new Color(0xffFF6600),
                    fontWeight: FontWeight.w700,
                    fontSize: ScreenUtil.getInstance().setSp(40)
                ),),
                new Container(
                  child: Text(
                    "/天",
                    style: new TextStyle(
                        color: new Color(0xffFF6600),
                        fontWeight: FontWeight.w700,
                        fontSize: ScreenUtil.getInstance().setSp(30)),
                  ),
                  margin: EdgeInsets.only(right: ScreenUtil.getInstance().setWidth(40)),
                ),

              ],
            ),
          ),

          new Container(
            alignment: Alignment.topLeft,
            child: Text(model.description,

              style: new TextStyle(
                  color: new Color(0xff999999),
                  fontSize: ScreenUtil.getInstance().setSp(26)),
            ),
            margin: EdgeInsets.fromLTRB(ScreenUtil.getInstance().setWidth(40), ScreenUtil.getInstance().setHeight(40), 0, ScreenUtil.getInstance().setHeight(20)),
          ),
          new Row(children: <Widget>[
            new Container(
              child: new FlatButton(
//                padding: EdgeInsets.fromLTRB(0, 5, 0, 5),
                  onPressed: () {},
                  color: new Color(0x1aFF6600),
                  shape: new RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(
                          ScreenUtil.getInstance().setWidth(5))),
                  child: new Text(
                    model.labels[0],
                    softWrap: false,
                    style: new TextStyle(
                      color: new Color(0xffFF6600),
                      fontSize: ScreenUtil.getInstance().setSp(24),
                    ),
                  )),
              width: ScreenUtil.getInstance().setWidth(126),
              height: ScreenUtil.getInstance().setHeight(40),
              margin: EdgeInsets.fromLTRB(
                  ScreenUtil.getInstance().setWidth(40),
                  0,
                  ScreenUtil.getInstance().setWidth(30),
                  0),
            ),
            new Container(
              child: new FlatButton(

//                  padding: EdgeInsets.fromLTRB(0, 5, 0, 5),
                  onPressed: () {},
                  color: new Color(0x1aFF6600),
                  shape: new RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(
                          ScreenUtil.getInstance().setWidth(5))),
                  child: new Container(
              width: ScreenUtil.getInstance().setWidth(126) ,
                    child: new Text(
                      model.labels[1],
                      softWrap: false,
                      style: new TextStyle(
                        color: new Color(0xffFF6600),
                        fontSize: ScreenUtil.getInstance().setSp(24),
                      ),
                      textAlign: TextAlign.center,
                    ),
                  )),
              width: ScreenUtil.getInstance().setWidth(126),
              height: ScreenUtil.getInstance().setHeight(40),
              margin: EdgeInsets.fromLTRB(
                  0,
                  0,
                  ScreenUtil.getInstance().setWidth(60),
                  0),
            ),
            Text(model.peoples.toString()+"人已报名",style: new TextStyle(
              color: new Color(0xff999999),
              fontSize: ScreenUtil.getInstance().setSp(26),
            ),),
          ],),
          new Container(margin:EdgeInsets.only(bottom: ScreenUtil.getInstance().setHeight(40)),),
        ],
      );
    }else{
      return  new ListTile(
          title: new Text("我擦"),
      );
    }


  }
}
