class Autogenerated {
  int status;
  String msg;
  List<Data> data;

  Autogenerated({this.status, this.msg, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    msg = json['msg'];
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['msg'] = this.msg;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int id;
  String title;
  String description;
  String money;
  String unit;
  List<String> labels;
  int peoples;

  Data(
      {this.id,
        this.title,
        this.description,
        this.money,
        this.unit,
        this.labels,
        this.peoples});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    description = json['description'];
    money = json['money'];
    unit = json['unit'];
    labels = json['labels'].cast<String>();
    peoples = json['peoples'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['description'] = this.description;
    data['money'] = this.money;
    data['unit'] = this.unit;
    data['labels'] = this.labels;
    data['peoples'] = this.peoples;
    return data;
  }
}
